server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: fva1opn.
  jpa:
    open-in-view: on
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:db.migration/changelog.yaml